### ISSUE TITLE
value out of range

### ISSUE THREAD

**Issue by jooyg62** [Vonng/pgbouncer_exporter#1]
I can't scrap the stats part, why?
Otherwise, part is not scrapped. No error message is displayed.

I will tell you the specifications.

------------------------------------------------------
Version list:
used pgbouncer_exporter version : v0.0.1
pgbouncer version: 1.9.0 
psql (PostgreSQL) 9.2.24

this is [show stats;] display value

-[ RECORD 1 ]-----+---------------------
database | ******
total_xact_count | 1002714
total_query_count | 1022148
total_received | 783936303
total_sent | 1659890576
total_xact_time | 306458282
total_query_time | 280741535
total_wait_time | 5574247036117366727
avg_xact_count | 0
avg_query_count | 0
avg_recv | 372
avg_sent | 306
avg_xact_time | 340
avg_query_time | 340
avg_wait_time | 102565085899
-[ RECORD 2 ]-----+---------------------
database | *****
total_xact_count | 199095964
total_query_count | 199295332
total_received | 115777317739
total_sent | 305395696030
total_xact_time | 62941448324
total_query_time | 62830581092
total_wait_time | 16492311827424936337
avg_xact_count | 125
avg_query_count | 125
avg_recv | 81171
avg_sent | 172590
avg_xact_time | 383
avg_query_time | 381
avg_wait_time | 102564663976
-[ RECORD 3 ]-----+---------------------
database | pgbouncer
total_xact_count | 304170
total_query_count | 304170
total_received | 0
total_sent | 0
total_xact_time | 0
total_query_time | 0
total_wait_time | 0
avg_xact_count | 0
avg_query_count | 0
avg_recv | 0
avg_sent | 0
avg_xact_time | 0
avg_query_time | 0
avg_wait_time | 0
-[ RECORD 4 ]-----+---------------------
database | postgres
total_xact_count | 0
total_query_count | 0
total_received | 0
total_sent | 0
total_xact_time | 0
total_query_time | 0
total_wait_time | 1064
avg_xact_count | 0
avg_query_count | 0
avg_recv | 0
avg_sent | 0
avg_xact_time | 0
avg_query_time | 0
avg_wait_time | 0

**Comment by Vonng** [comment]
In some case, you have to launch a real connection to specific pool to add a stat entry. 
I'd suggest using https://github.com/Vonng/pg_exporter  instead, which support both pgbouncer and postgres and much more robust.
